<?php
/**
 * @file
 * Code for the eiq partners feature.
 */

include_once 'eiq_partners.features.inc';

function eiq_partners_menu() {
  $items = array();

  $items['kiva-zip/get-started'] = array(
    'page callback' => '_eiq_partners_check',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  $items['kiva-zip/no-thanks'] = array(
    'page callback' => '_eiq_partners_nothanks',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}


function _eiq_partners_check() {
  global $user;

  if($user->uid == '0'){
    $_SESSION['partner'] = arg(0);
    setcookie("partner", arg(0) . '/get-started', time()+3600, "/");
    drupal_goto('user/login');
  }else{
    $_SESSION['partner'] = arg(0);
    //drupal_goto('user/'.$user->uid.'/apply');
    return _eiq_partners_startapp_form();
    //return drupal_get_form('data_company_node_form');
  }
  return;


}


function _eiq_partners_startapp_form() {
  global $user;
  $node = (object) array('uid' => $user->uid, 'name' => (isset($user->name) ? $user->name : ''), 'type' => 'data_company', 'language' => LANGUAGE_NONE);
  $form_state['build_info']['args'] = array($node);
  form_load_include($form_state, 'inc', 'node', 'node.pages');
  return drupal_build_form('data_company_node_form', $form_state);
}


function eiq_partners_form_data_company_node_form_alter(&$form, &$form_state) {
  //dpm($form['#fieldgroups']['group_constituents']);
  //dpm($form_state);
  //$form['field_product_id']['#type'] = 'hidden';
  global $user;
  if ($user->uid == 1) {
    drupal_set_message("WARNING: You are logged in as user 1. This commerce page will not work correctly. Please login or masquerade as another user.");
  }
  $partner = "client";
  switch (arg(0)) {
    case "kiva-zip":
      //dpm($form);
      $partner = arg(0);
      $fields = array("body",
        "field_company_type",
        "field_dba",
        //"field_disclaimer",
        "field_fein",
        "field_website",
        "field_year_of_legal_formation",
        "field_agree_final",
        "field_company_address",
        "field_company_phone",
        "field_facebook",
        "field_linkedin",
        //"field_product_id",
        "field_state_incorp",
        "field_state_registration",
        "field_twitter",
        //"field_invite_officers",
        "field_purchase_completed",
        "field_industry"
      );
      $form = _eiq_partners_hide_fields($form, $fields);
      //$form['field_invite_officers']['#type'] = 'hidden';
      //$form['#groups']['group_constituents']->format_type = 'hidden';
      unset($form['field_invite_officers']['und']['add_more']);
      $form['field_invite_officers']['und']['#title'] = 'Invite Officer';

      // set partner product information
      $form['commerce_node_checkout_product']['#default_value'] = '2';
      $form['commerce_node_checkout_product']['#access'] = FALSE;
      //$form['commerce_node_checkout_product']['#disabled'] = TRUE;
      $form['field_product_id']['und']['#default_value'][0] = '2';
      $form['field_product_id']['#access'] = FALSE;
      //$form['field_product_id']['#disabled'] = TRUE;
      $form['field_disclaimer']['und']['#title'] = "I agree to Kiva-specific EarlyIQ Disclaimer.";

      context_set('eiq_commerce', 'partner', $partner);
      break;
  }

  context_set('eiq_commerce', 'partner', $partner);
  return $form;
}

function _eiq_partners_hide_fields($form, $fields) {
  foreach ($fields as $field) {
    //$form[$field]['#access'] = FALSE;
    unset($form[$field]);
  }
  return $form;
}

function eiq_partners_form_commerce_checkout_form_checkout_alter(&$form, &$form_state) {
  //dpm($form);
  if (isset($_SESSION['partner']) && $_SESSION['partner'] == "kiva-zip") {
    $form['customer_profile_billing']['#access'] = FALSE;
    $form['commerce_payment']['#type'] = 'hidden';
  }
}

function eiq_partners_form_data_person_node_form_alter(&$form, &$form_state) {
  //dpm($form['#fieldgroups']['group_constituents']);
  //dpm($form);
  //$form['field_product_id']['#type'] = 'hidden';
  if (isset($form['field_company']['und'][0]['nid']['#default_value'])) {
    $company_node = node_load($form['field_company']['und'][0]['nid']['#default_value']);
    $product_id = $company_node->field_product_id['und'][0]['product_id'];
    $partner = "client";
    switch ($product_id) {
      case "2": // works for kiva-zip partner
        $partner = 'kiva-zip';
        $fields = array(
          'title',
          //'field_company',
          //'field_dob',
          'field_email_address',
          'field_gender',
          'field_kba',
          //'field_name_first',
          //'field_name_last',
          'field_name_maiden',
          //'field_name_middle',
          'field_name_suffix',
          //'field_ssn',
          //'field_address',
          //'field_agree_final',
          'field_citizenship',
          'field_civil',
          //'field_criminal',
          'field_education',
          'field_employment',
          'field_linkedin_profile',
          //'field_convictions',
        );
        $form = _eiq_partners_hide_fields($form, $fields);
        unset($form['field_address']['und'][0]['field_address_dates']);
        unset($form['field_address']['und']['add_more']);
        $form['field_address']['und']['#title'] = "Current Home Address";
        $form['#groups']['group_personal_info']->format_type = 'hidden';
        // hiding nested fields
        _eiq_partners_hide_field($form['field_criminal']['und'], "field_criminal_description");
        _eiq_partners_hide_field($form['field_criminal']['und'], "field_criminal_level");
        _eiq_partners_hide_field($form['field_criminal']['und'], "field_criminal_type");
        _eiq_partners_hide_field($form['field_criminal']['und'], "field_criminal_year");

        $form['instruction'] = array(
        	'#type' => 'item',
            '#markup' => t('<h3>Please be sure that all the personal information you enter is true, accurate, and complete. Once you click Submit, we’ll validate your information and you’ll be on to the last step.</h3>')
        );
	        //           $form['group_label'] = array(
	        // 	'#type' => 'item',
	        //     '#title' => t('<div>Applicant Information:</div>'),
	        //     '#weight' => '2',
	        // );
        $form['field_company']['und']['#title'] = "Company:";

        $form['field_agree_final']['und']['#title'] = "By checking this box, you are affirming that all the information you have provided is complete and accurate and you give your explicit permission for the information to be used in accordance with our <a href='/terms-use' target='_new'>Terms of Use</a>. You understand that the information you have provided will be used to perform background research and validation of the answers submitted in your loan application and your Trustee's endorsement to be listed on the Kiva Zip lending site. This is not a credit report or credit check, nor will your credit records be accessed.";
        break;
    }
    context_set('eiq_commerce', 'partner', $partner);
        $form['cancel'] = array(
          '#type' => 'markup',
          '#access' => TRUE,
          '#markup' => '<a href="/' . context_get('eiq_commerce', 'partner') . '/no-thanks?destination=' . urlencode(request_uri()) . '" id="edit-submit-cancel">No Thanks</a>',
          '#weight' => 160,
        );
  } else {
    drupal_set_message("No product is associated with this application. Please contact the site admin.");
  }
}


function _eiq_partners_hide_field(&$field, $hide_field) {
  foreach ($field as $key => $value) {
    if (is_numeric($key)) {
      unset($field[$key][$hide_field]);
    }
  }
  return $field;
}

function eiq_partners_form_user_profile_form_alter(&$form, &$form_state) {
  global $user;
  $account = user_load($user->uid);
  //set context for co-branding
  _eiq_partners_get_partner($account);

  $form['field_name_first']['#type'] = 'hidden';
  $form['field_name_last']['#type'] = 'hidden';
  $form['account']['mail']['#type'] = 'hidden';
  if (isset($_GET['pass-reset-token'])) {
    $form['cancel'] = array(
      '#type' => 'markup',
      '#access' => TRUE,
      '#markup' => '<a href="/' . context_get('eiq_commerce', 'partner') . '/no-thanks?destination=' . urlencode(request_uri()) . '" id="edit-submit-cancel">No Thanks</a>',
      '#weight' => 160,
    );
  }

  // setup redirect to correct Application if session exists for a partner
  // and must be after password reset is completed
  if (!isset($_SESSION['pass_reset_' . $user->uid]) && isset($_SESSION['partner'])) {
      //dpm("partner redirect");
      _em_apply_redirect_id($account);
  }
}
function eiq_partners_form_user_pass_reset_alter(&$form, &$form_state) {
  $form['message']['#markup'] = "<h2>Welcome. Thank you for your interest.</h2><p>As part of the process for applying to be listed on Kiva Zip, we ask that you complete this simple 3-Step identity and background validation process.The information you enter will be <u>kept confidential</u> and <u>will not be shared</u> with anyone outside of Kiva Zip and its business partners for the specific use of verifying your identity and background as described in our Terms and Conditions. Completing the steps should take no more than 5 minutes. So let’s get started!</p>";
  $form['actions']['submit']['#value'] = "Get Started";
  $form['cancel'] = array(
    '#type' => 'markup',
    '#access' => TRUE,
    '#markup' => '<a href="/' . context_get('eiq_commerce', 'partner') . '/no-thanks?destination=' . urlencode(request_uri()) . '" id="edit-submit-cancel">No Thanks</a>',
    '#weight' => 160,
  );

}

function _eiq_partners_form_cancel() {
  	module_load_include('pages.inc', 'user');
	user_logout();
    drupal_goto('user/logout');
}

/**
 * Implements hook_user_login
 */
/*function eiq_partners_user_login(&$edit, $account) {
  dpm("logging in");
  _eiq_partners_get_partner($account);
}*/

/**
 * Implements hook_init
 */
function eiq_partners_init() {
  if (arg(0) == "user" && arg(1) == "reset") {
    $account = user_load(arg(2));
    _eiq_partners_get_partner($account);
  }
}


function _eiq_partners_get_partner($account) {
  //send them to person_data/kba form
  $result = db_select('node','d')
      ->fields('d')
      ->condition('type','data_person','=')
      ->condition('uid', $account->uid,'=')
      ->execute();

  while($record = $result->fetchAssoc()) {
    if($record['nid']){
      $nid = $record['nid'];

      $dataPerson = node_load($nid);
      if(!empty($dataPerson)){
        $company_node = node_load($dataPerson->field_company['und'][0]['nid']);
        $product_id = $company_node->field_product_id['und'][0]['product_id'];
        $partner = "client";
        switch ($product_id) {
          case "2": // works for kiva-zip partner
            $partner = 'kiva-zip';
            break;
        }
        context_set('eiq_commerce', 'partner', $partner);
      }
    }
  }

}

function _eiq_partners_notify_analyst($node, $uid, $status) {
  $partner_admin = user_load($uid);
  mail($partner_admin->mail, "kiva-zip app " . $status, url('node/' . $node['nid']));
}

function _eiq_partners_nothanks() {
  $output  = "<h2>Your application is not complete.</h2>";
  $output .= "<p>If you want to continue with the application, click the Go Back button and we’ll continue with your application.  If you’re not interested in completing the application, click Leave and we’ll stop the process.</p>";
  $output .= '<a href="' . urldecode($_GET['destination']) . '" class="form-submit">Go Back</a>';
  $output .= '<a href="/user/logout" id="edit-submit-cancel">Leave</a>';
  return $output;
}