<?php
/**
 * @file
 * Code for the eiq partners feature.
 */

include_once 'eiq_partners.features.inc';

function eiq_partners_menu() {
  $items = array();

  $items['kiva-zip/get-started'] = array(
    'page callback' => '_eiq_partners_check',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );
  return $items;
}


function _eiq_partners_check() {
  global $user;

  if($user->uid == '0'){
    $_SESSION['destination'] = arg(0);
    setcookie("destination", arg(0) . '/get-started', time()+3600, "/");
    drupal_goto('user/login');
  }else{
    $_SESSION['partner'] = arg(0);
    return _eiq_partners_startapp_form();
    //return drupal_get_form('data_company_node_form');
  }
  return;


}


function _eiq_partners_startapp_form() {
  global $user;
  $node = (object) array('uid' => $user->uid, 'name' => (isset($user->name) ? $user->name : ''), 'type' => 'data_company', 'language' => LANGUAGE_NONE);
  $form_state['build_info']['args'] = array($node);
  form_load_include($form_state, 'inc', 'node', 'node.pages');
  return drupal_build_form('data_company_node_form', $form_state);
}


function eiq_partners_form_data_company_node_form_alter(&$form, &$form_state) {
  //dpm($form['#fieldgroups']['group_constituents']);
  //dpm($form_state);
  //$form['field_product_id']['#type'] = 'hidden';
  switch (arg(0)) {
    case "kiva-zip":
      //dpm($form);
      $fields = array("body",
        "field_company_type",
        "field_dba",
        //"field_disclaimer",
        "field_fein",
        "field_website",
        "field_year_of_legal_formation",
        "field_agree_final",
        "field_company_address",
        "field_company_phone",
        "field_facebook",
        "field_linkedin",
        //"field_product_id",
        "field_state_incorp",
        "field_state_registration",
        "field_twitter",
        //"field_invite_officers",
        "field_purchase_completed",
        "field_industry"
      );
      $form = _eiq_partners_hide_fields($form, $fields);
      //$form['field_invite_officers']['#type'] = 'hidden';
      //$form['#groups']['group_constituents']->format_type = 'hidden';
      unset($form['field_invite_officers']['und']['add_more']);
      $form['field_invite_officers']['und']['#title'] = 'Invite Officer';

      // set partner product information
      $form['commerce_node_checkout_product']['#default_value'] = '2';
      $form['commerce_node_checkout_product']['#access'] = FALSE;
      //$form['commerce_node_checkout_product']['#disabled'] = TRUE;
      $form['field_product_id']['und']['#default_value'][0] = '2';
      $form['field_product_id']['#access'] = FALSE;
      //$form['field_product_id']['#disabled'] = TRUE;
      $form['field_disclaimer']['und']['#title'] = "I agree to Kiva-specific EarlyIQ Disclaimer.";
      break;
  }

  return $form;
}

function _eiq_partners_hide_fields($form, $fields) {
  foreach ($fields as $field) {
    //$form[$field]['#access'] = FALSE;
    unset($form[$field]);
  }
  return $form;
}

function eiq_partners_form_commerce_checkout_form_checkout_alter(&$form, &$form_state) {
  //dpm($form);
  if (isset($_SESSION['partner']) && $_SESSION['partner'] == "kiva-zip") {
    $form['customer_profile_billing']['#access'] = FALSE;
    $form['commerce_payment']['#type'] = 'hidden';
  }
}

function eiq_partners_form_data_person_node_form_alter(&$form, &$form_state) {
  //dpm($form['#fieldgroups']['group_constituents']);
  //dpm($form);
  //$form['field_product_id']['#type'] = 'hidden';
  switch ($_SESSION['partner']) {
    case "kiva-zip":
      $fields = array(
        'title',
        //'field_company',
        //'field_dob',
        'field_email_address',
        'field_gender',
        'field_kba',
        //'field_name_first',
        //'field_name_last',
        'field_name_maiden',
        //'field_name_middle',
        'field_name_suffix',
        //'field_ssn',
        //'field_address',
        'field_agree_final',
        'field_citizenship',
        'field_civil',
        'field_criminal',
        'field_education',
        'field_employment',
        'field_linkedin_profile',
        //'field_convictions',
      );
      $form = _eiq_partners_hide_fields($form, $fields);
      unset($form['field_address']['und'][0]['field_address_dates']);
      unset($form['field_address']['und']['add_more']);
      $form['#groups']['group_personal_info']->format_type = 'hidden';
      break;
  }
}