<?php

function em_webservices_menu() {
  $items = array();
  
  $items['webservices/test/kba'] = array(
    'page callback' => 'em_webservices_kba_test',
    'access callback' => TRUE,
    'description' => 'KBA Testing form',
    'file' => 'kba/kba.inc',
    'type' => MENU_CALLBACK
  );

  $items['verification/%'] = array(
    'page callback' => 'em_webservices_verification',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'description' => 'KBA form',
    'file' => 'kba/kba.inc',
    'type' => MENU_CALLBACK
  );
  $items['verification/%/status'] = array(
    'page callback' => 'em_webservices_status',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'file' => 'kba/kba.inc',
    'type' => MENU_CALLBACK
  );
  
  $items['webservices/test/experian'] = array(
    'page callback' => 'em_webservices_experian',
    'access callback' => TRUE,
    'description' => 'Experian Civil Form',
    'file' => 'experian/experian.inc',
    'type' => MENU_CALLBACK
  );
   
  return $items;
}

function em_webservices_status($nid){
	
	$html = "<p>Don't worry, there's probably a simple reason why this
	happened. This does not mean your application has
	been rejected. We'll be in touch with you regarding
	next steps in your application process. Thank you.</p>";
	
	return $html;
}

function em_webservices_verification($nid) {
	global $user;
	$node = node_load($nid);
	if (($user->uid == $node->uid) && ($node->type == 'data_person')){
		unset($node);
		return drupal_get_form("kba_wizard",$nid);
	}else{
		unset($node);
		return "Access Denied, you do not have permissions to this data";
	}
}

function em_webservices_kba_test(){
	global $user;
	return drupal_get_form("kba_wizard");
}

// Experian 
function em_webservices_experian() {
	global $user;
  return drupal_get_form("experian_test");
}