<?php

function em_webservices_menu() {
  $items = array();
  
  $items['webservices/test/kba'] = array(
    'page callback' => 'em_webservices_kba_test',
    'access callback' => TRUE,
    'description' => 'KBA Testing form',
    'file' => 'kba/kba.inc',
    'type' => MENU_CALLBACK
  );

  $items['verification'] = array(
    'page callback' => 'em_webservices_verification',
    'access callback' => TRUE,
    'description' => 'KBA form',
    'file' => 'kba/kba.inc',
    'type' => MENU_CALLBACK
  );
  
  $items['webservices/test/experian'] = array(
    'page callback' => 'em_webservices_experian',
    'access callback' => TRUE,
    'description' => 'Experian Civil Form',
    'file' => 'experian/experian.inc',
    'type' => MENU_CALLBACK
  );
   
  return $items;
}

function em_webservices_verification() {
	global $user;
	return drupal_get_form("kba_wizard");
}

function em_webservices_kba_test(){
	global $user;
	return drupal_get_form("kba_wizard");
}

// Experian 
function em_webservices_experian() {
	global $user;
  return drupal_get_form("experian_test");
}