<?php

function em_webservices_menu() {
  $items = array();

/*
  $items['webservices/test'] = array(
    'page callback' => 'em_webservices_test',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK
  );
*/
  
  $items['webservices/test/kba'] = array(
    'page callback' => 'em_webservices_kba_test',
    'access callback' => TRUE,
    'description' => 'KBA Testing form',
    'file' => 'kba/kba.inc',
    'type' => MENU_CALLBACK
  );
    
  return $items;
}

function em_webservices_kba_test(){
	global $user;
	return drupal_get_form("kba_wizard");
}

/***
 * 
 * @param array $personData Data from the person that needs to be authenticated
 **/
function em_webservices_kba($personData, $callback) {
  global $user;
  
  
}